/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.ulpgc.dis.practica10;

import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Andres
 */
public class main extends javax.swing.JFrame {

    FileNameExtensionFilter filtro = null;
    DefaultListModel model = new DefaultListModel();
    String originalFolder;
    String selectFile;
    long contentSize;
    ArrayList<String> files;
    HashMap<String, String> map = new HashMap<>();
    int[] index;
    int j, x = 0;



    /**
     * Creates new form main
     */
    public main() {
        initComponents();

        list.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        fileInfo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitMenu = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        compressMenu = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        informationOption = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(list);

        fileInfo.setText("Select the files you would like to compress");

        fileMenu.setText("File");

        openMenu.setText("Open");
        openMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuActionPerformed(evt);
            }
        });
        fileMenu.add(openMenu);
        fileMenu.add(jSeparator1);

        exitMenu.setText("Exit");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenu);

        jMenuBar1.add(fileMenu);

        editMenu.setText("Edit");

        compressMenu.setText("Compress");
        compressMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compressMenuActionPerformed(evt);
            }
        });
        editMenu.add(compressMenu);

        jMenuBar1.add(editMenu);

        helpMenu.setText("Help");

        informationOption.setText("Information");
        informationOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informationOptionActionPerformed(evt);
            }
        });
        helpMenu.add(informationOption);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fileInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(fileInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fileInfo.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuActionPerformed
        // TODO add your handling code here:
        model.removeAllElements();

        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fc.setAcceptAllFileFilterUsed(false);

        int res = fc.showOpenDialog(null);
        if (res == JFileChooser.APPROVE_OPTION) {
            File fichero = fc.getSelectedFile();
            originalFolder = fichero.getName();
            for (File contenido : fichero.listFiles()) {
                if (contenido.isFile()) {
                    model.addElement(contenido.getName());
                    map.put(contenido.getName(), contenido.getAbsoluteFile().toString());
                }
            }

            fileInfo.setVisible(true);
            pack();

            list.addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {
                    boolean flag = e.getValueIsAdjusting();

                    index = list.getSelectedIndices();
                    j = 0;

                    if (index.length > 0 && flag) {
                        files = new ArrayList<>();
                        while (j < index.length) {
                            String name = list.getModel().getElementAt(index[j]);
                            for (HashMap.Entry<String, String> entry : map.entrySet()) {
                                if (name.equals(entry.getKey())) {
                                    
                                    files.add(entry.getValue());
                                }
                            }
                            j++;
                        }
                    }
                }

            });
        }
    }//GEN-LAST:event_openMenuActionPerformed

    private void compressMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compressMenuActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
        JFileChooser fc = new JFileChooser();

        fc.setDialogTitle("Compress");
        fc.setSelectedFile(new File(originalFolder));

        int res = fc.showOpenDialog(null);
        if (res == JFileChooser.APPROVE_OPTION) {
            selectFile = fc.getSelectedFile().getAbsoluteFile() + ".zip";
            
            progress tarea2 = new progress(this, false, files, selectFile);
            tarea2.start();
        tarea2.setVisible(true);
        
            
            
            tarea2.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        }
    }//GEN-LAST:event_compressMenuActionPerformed

    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "Would you like to close the app?", "Close application", JOptionPane.YES_NO_OPTION) == 0)
            System.exit(0);
    }//GEN-LAST:event_exitMenuActionPerformed

    private void informationOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informationOptionActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane,
                "This app allows to compress files from a directory"
                + "\nHow to use it:\n"
                + "\t 1- Using the menu Open (Alt+O) for selectin the directory where you want to work."
                + "\n \n"
                + "\t 2- Select from the list above, the files you would like to compress."
                + "\n \n"
                + "\t 3- For compressing your files you would have to Edit and select the option in the submenu, and select where you would like to compress the files."
                + "\n \t\t\t\t\t The file will compress by default on .zip format"
                + "\n \n"
                + "\t 4- You can exit the program by using the menu Open (Alt+O) and the option Exit (ESC)."
                + "\n \n"
                + "\t You can view more info. on the link: " + "https://github.com/ancabdia/Practica_10_DIU.git",
                "Help information", JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_informationOptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem compressMenu;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JLabel fileInfo;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem informationOption;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JList<String> list;
    private javax.swing.JMenuItem openMenu;
    // End of variables declaration//GEN-END:variables
}
